name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: "Label when approved"
    runs-on: ubuntu-latest
    outputs:
      isApprovedByAnyone: ${{ steps.label-when-approved-by-anyone.outputs.isApproved }}
    env:
      APPROVALS: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ADD_LABEL: "approved"
    steps:
      - name: Label when approved by anyone
        uses: TobKed/label-when-approved-action@v1.2
        id: label-when-approved-by-anyone
